# Generated by Django 5.0.6 on 2024-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scar1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('off', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('off', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('off', models.IntegerField()),
            ],
        ),
    ]
