# Generated by Django 5.0.6 on 2024-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scar1', '0002_dairyitems_fruits_vegetables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Babycare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('off', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
